platform :ios, '11.0'
inhibit_all_warnings!

target 'Financies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'Firebase/InAppMessagingDisplay'
  
  #pod 'FacebookLogin'
  pod 'AccountKit'
  
  pod 'GoogleSignIn'
end
